version: '3.8'
services:
  backend:
    container_name: backend
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3210:3030'
    restart: always
    volumes:
      - ./backend:/backend-docker
    environment:
      DB_URL: mongodb://db/database
    networks:
      - app-network

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - database:/data/db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4321:4040"
    restart: always
    volumes:
      - ./frontend:/frontend-docker
    networks:
      - app-network

volumes:
  database:

networks:
  app-network:
    driver: bridge